name: upstream

on:
  pull_request:
    branches: [master, main]

jobs:
  canary-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: kommons

      - uses: actions/checkout@v4
        with:
          repository: flanksource/canary-checker
          path: canary-checker
          branch: master

      - uses: actions/setup-go@v4
        with:
          go-version: 1.22.x

      - name: replace Module
        run: |
          cd canary-checker
          module=$(cat go.mod | grep github.com/flanksource/kommons | awk '{print $2}')
          go mod edit -replace github.com/flanksource/kommons@$module=$GITHUB_WORKSPACE/kommons
          cat go.mod
          go mod tidy

      - name: Test Make Linux
        working-directory: ./canary-checker
        run: make linux

      - name: Build
        working-directory: ./canary-checker
        run: make
